version: "3"
services:
  discord-audio-pipe:
    image: axelcypher/discord-audio-pipe:latest
    container_name: discord-audio-pipe
    devices:
      - "/dev/snd"
    restart: always
    environment:
      HOST: 10.2.0.25
    volumes:
      - type: bind
        source: /home/tpendzialek/discord-audio-pipe/config/token.txt:/app/token.txt
        

